version: '3'
services:
  rabbitmq:    
    image: rabbitmq:latest
    container_name: rabbitmq_andrei
    hostname: andrei_host
    ports:
      - "5671:5672" 
  rabbitmq-management:
    image: rabbitmq:3-management
    container_name: rabbitmq_andrei_management
    hostname: andrei_host
    ports:
      - "8080:15672"   
    depends_on:
      - rabbitmq   

